### ISSUE TITLE
Unity to be unable to persist setting changes

### ISSUE THREAD

**Issue by mikedg1** [PixelVision8/UnityRunner#1]
Symptoms:
Unity shows multiple warnings on project load "Ignoring asset refresh of [each setting file] because that file or it's directory couldn't be found"
Settings do not persist when you click save project
Settings to not persist when you exit Unity

Reproduce:
Change project settings, such as package name for Android. 
Exit Unity. 
Reload the project, observe that the original setting value is back.

A build and play works fine  but the original settings still return after reloading the project.

This occurs on multiple Unity versions and multiple PCs

Resolution:
This can be resolved by deleting all .meta files from the /ProjectSettings directory

**Comment by jessefreeman** [comment]
This should be fixed now. Modified the .gitignore file to ignore all .meta files in the ProjectSettings directory.
